export type Publication = {
	title: string;
	href?: string;
	authors: string;
	venue: string;
	year: number;
	award?: string;
};

export const publications: Publication[] = [
	{
		title:
			'"I Choose to Live, for Life Itself": Understanding Agency of Home-Based Care Patients Through Information Practices and Relational Dynamics in Care Networks',
		href: '/projects/chi26',
		authors: 'Sung-In Kim*, Joonyoung Park*, Bogoan Kim, Hwajung Hong',
		venue: 'CHI 2026',
		year: 2026,
		award: 'Honorable Mention Award'
	},
	{
		title:
			'Enhancing Patient Participation in Emergency Department through Patient-Friendly Clinical Notes Generated by Large Language Models',
		href: 'https://www.nature.com/articles/s41598-025-31113-y',
		authors:
			'Sung-In Kim, Joonyoung Park, Taewan Kim, Woosuk Seo, Taerim Kim, Won Chul Cha, Hwajung Hong',
		venue: 'Scientific Reports 16',
		year: 2026
	},
	{
		title: 'NoRe: Augmenting Journaling Experience with Generative AI for Music Creation',
		href: '/projects/nore',
		authors: 'Joonyoung Park*, Hyewon Cho*, Hyehyun Chu*, YeEun Lee, Hajin Lim',
		venue: 'DIS 2025',
		year: 2025
	},
	{
		title: 'NoRe: 일기 기반 AI 음악 생성 앱을 위한 디자인 제언',
		href: '/pdfs/hcik25nore.pdf',
		authors:
			'Joonyoung Park*, YeEun Lee*, Hyewon Cho*, Hyehyun Chu*, Jiin Cheon*, Jinsu Eun, Hajin Lim',
		venue: 'HCIK 2025',
		year: 2025
	}
];
